[ScalabilitySettings]
; Mobile-first scalability

[ShadowQuality@0]
r.ShadowQuality=0
r.Shadow.CSM.MaxCascades=0

[ShadowQuality@1]
r.ShadowQuality=2
r.Shadow.CSM.MaxCascades=1

[ShadowQuality@2]
r.ShadowQuality=3
r.Shadow.CSM.MaxCascades=2

[ShadowQuality@3]
r.ShadowQuality=5
r.Shadow.CSM.MaxCascades=4

[ViewDistanceQuality@0]
r.SkeletalMeshLODBias=2

[ViewDistanceQuality@1]
r.SkeletalMeshLODBias=1

[ViewDistanceQuality@2]
r.SkeletalMeshLODBias=0

[ViewDistanceQuality@3]
r.SkeletalMeshLODBias=0

[TextureQuality@0]
r.Streaming.MipBias=2
r.MaxAnisotropy=0

[TextureQuality@1]
r.Streaming.MipBias=1
r.MaxAnisotropy=2

[TextureQuality@2]
r.Streaming.MipBias=0
r.MaxAnisotropy=4

[TextureQuality@3]
r.Streaming.MipBias=0
r.MaxAnisotropy=8

[EffectsQuality@0]
r.ParticleLightComplexity=0
Niagara.QualityLevel=0

[EffectsQuality@1]
r.ParticleLightComplexity=1
Niagara.QualityLevel=1

[EffectsQuality@2]
r.ParticleLightComplexity=2
Niagara.QualityLevel=2

[EffectsQuality@3]
r.ParticleLightComplexity=2
Niagara.QualityLevel=3
